using System.Collections;
using UnityEngine;
using UnityEngine.Audio;

//This script is for the Mana Towers to generate mana

public class ManaTower : MonoBehaviour
{
    //audio stuff 
    public AudioSource audio;

    public Mana manaManager; //Refernce to Mana script

    private int towerManaAmount; //Base amount of mana generated by Mana Towers

    private float manaGenerationRate; //Base wait time for coroutine loops

    private bool makeMana = true; //Boolean for looping coroutine
    public bool active = true;

    //Starts the coroutine for mana generation when a Mana Tower is placed
    void Start()
    {
        if(manaManager == null)
            manaManager = FindObjectOfType<Mana>();
        StartCoroutine(GenerateMana());
    }

    /*
    Determines how much mana is generated by a Mana Tower.
    */
    public int DetermineTowerManaAmount()
    {
        towerManaAmount = 70;
        return towerManaAmount;
    }

    /*
    Determines the speed at which mana is generated.
    */
    private void DetermineManaGenerationRate()
    {
        manaGenerationRate = 10;
    }

    /*
    This coroutine is called separately for each Mana Tower placed.
    It calls the method for adding mana from the Mana script and 
    then pauses for the amount of seconds given in the method for 
    determining wait time.
    */
    IEnumerator GenerateMana()
    {
        while (makeMana)
        {
            Debug.Log("mana: " + manaManager.currentManaAmount);
            DetermineManaGenerationRate();
            DetermineTowerManaAmount();
            Debug.Log("mana: determinedGen");
            if(active)
            {
                manaManager.AddMana(towerManaAmount);
                audio.Play();
            }
            Debug.Log("mana: added");
            yield return new WaitForSeconds(manaGenerationRate);
            Debug.Log("mana: waited");
        }
    }

}
