using System.Collections;
using UnityEngine;
using UnityEngine.Audio;

//This script is for the Mana Towers to generate mana

public class ManaTower : MonoBehaviour
{
    //audio stuff 
    public AudioSource audio;

    public Mana manaManager; //Refernce to Mana script

    public int manaTowerLevel; //Current level of Mana Tower

    private int towerManaAmount; //Base amount of mana generated by Mana Towers
    private int boostedTowerManaAmount; //Amount added to mana generated after Mana Tower is upgraded

    private float manaGenerationRate; //Base wait time for coroutine loops
    private float boostedManaGenerationRate; //Used for decreasing wait time after Mana Tower is upgraded

    private bool makeMana = true; //Boolean for looping coroutine

    //Starts the coroutine for mana generation when a Mana Tower is placed
    void Start()
    {
        if(manaManager == null)
            manaManager = FindObjectOfType<Mana>();
        StartCoroutine(GenerateMana());
    }

    /*
    Determines how much mana is generated by a Mana Tower.
    At the default tower level (0), only 70 is produced.
    Increasing the tower level boosts this amount.
    */
    public int DetermineTowerManaAmount()
    {
        if (manaTowerLevel == 1)
        {
            boostedTowerManaAmount = 10;
        }
        else if (manaTowerLevel == 2)
        {
            boostedTowerManaAmount = 20;
        }
        else if (manaTowerLevel == 3)
        {
            boostedTowerManaAmount = 40;
        }
        else if (manaTowerLevel == 4)
        {
            boostedTowerManaAmount = 80;
        }
        else if (manaTowerLevel == 5)
        {
            boostedTowerManaAmount = 160;
        }

        towerManaAmount = 70 + boostedTowerManaAmount;
        return towerManaAmount;
    }

    /*
    Determines the speed at which mana is generated.
    At the default tower level (0), this occurs every ten seconds.
    Increasing the tower level speeds up the generation rate.
    */
    private void DetermineManaGenerationRate()
    {
        if (manaTowerLevel == 1)
        {
            boostedManaGenerationRate = 0.5f;
        }
        else if (manaTowerLevel == 2)
        {
            boostedManaGenerationRate = 1.0f;
        }
        else if (manaTowerLevel == 3)
        {
            boostedManaGenerationRate = 2.0f;
        }
        else if (manaTowerLevel == 4)
        {
            boostedManaGenerationRate = 4.0f;
        }
        else if (manaTowerLevel == 5)
        {
            boostedManaGenerationRate = 8.0f;
        }

        manaGenerationRate = 10 / (1 + boostedManaGenerationRate);
    }

    /*
    This coroutine is called separately for each Mana Tower placed.
    It calls the method for adding mana from the Mana script and 
    then pauses for the amount of seconds given in the method for 
    determining wait time.
    */
    IEnumerator GenerateMana()
    {
        while (makeMana)
        {
            Debug.Log("mana: " + manaManager.currentManaAmount);
            DetermineManaGenerationRate();
            DetermineTowerManaAmount();
            Debug.Log("mana: determinedGen");
            manaManager.AddMana(towerManaAmount);
            audio.Play();
            Debug.Log("mana: added");
            yield return new WaitForSeconds(manaGenerationRate);
            Debug.Log("mana: waited");
        }
    }

}
